services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  app:
    image: "lilbapo/multipost:backend"
    ports:
      - '8080:8080'
    environment:
      spring.datasource.url: 'jdbc:mysql://mysql:3306/mydatabase'
      REDIRECT_URI: 'http://localhost:4200'
      FRONTEND_URI: 'http://localhost:4200'
    depends_on:
      - 'mysql'
