services:
  mysql:
    image: 'mysql:latest'
    env_file:
      - .env
    ports:
      - '3306:3306'
  app:
    image: 'lilbapo/multipost:backend-production'
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - 'mysql'
  frontend:
      image: 'lilbapo/multipost:frontend-production'
      ports:
        - '4200:4200'
      env_file:
        - .env
      depends_on:
      - 'app'