spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mydatabase
    username: root
    password: verysecret
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG